title: GitHub Öğrenmeye Mi Geldik?
author: sedatmertk
email: sedatmert@live.com
description: > # this means to ignore newlines until "baseurl:"
  Ya şimdi açtık GitHub'ı. Ama bir bakıyorum bunu neden yaptık?
  Neden böyle? vs.
  Sonra taşlar yerine oturuyor...

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
